INSERT INTO public.fiscal_catalog_items (catalog_type, code, label, description, sort_order, is_active)
VALUES
    ('pis_cst', '01', '01', 'Operacao tributavel com aliquota basica', 10, true),
    ('pis_cst', '02', '02', 'Operacao tributavel com aliquota diferenciada', 20, true),
    ('pis_cst', '03', '03', 'Operacao tributavel por unidade de medida de produto', 30, true),
    ('pis_cst', '04', '04', 'Operacao tributavel monofasica - revenda a aliquota zero', 40, true),
    ('pis_cst', '05', '05', 'Operacao tributavel por substituicao tributaria', 50, true),
    ('pis_cst', '06', '06', 'Operacao tributavel a aliquota zero', 60, true),
    ('pis_cst', '07', '07', 'Operacao isenta da contribuicao', 70, true),
    ('pis_cst', '08', '08', 'Operacao sem incidencia da contribuicao', 80, true),
    ('pis_cst', '09', '09', 'Operacao com suspensao da contribuicao', 90, true),
    ('pis_cst', '49', '49', 'Outras operacoes de saida', 100, true),
    ('pis_cst', '50', '50', 'Operacao com direito a credito - Vinculada exclusivamente a receita tributada no mercado interno', 110, true),
    ('pis_cst', '51', '51', 'Operacao com direito a credito - Vinculada exclusivamente a receita nao-tributada no mercado interno', 120, true),
    ('pis_cst', '52', '52', 'Operacao com direito a credito - Vinculada exclusivamente a receita de exportacao', 130, true),
    ('pis_cst', '53', '53', 'Operacao com direito a credito - Vinculada a receitas tributadas e nao-tributadas no mercado interno', 140, true),
    ('pis_cst', '54', '54', 'Operacao com direito a credito - Vinculada a receitas tributadas no mercado interno e de exportacao', 150, true),
    ('pis_cst', '55', '55', 'Operacao com direito a credito - Vinculada a receitas nao-tributadas no mercado interno e de exportacao', 160, true),
    ('pis_cst', '56', '56', 'Operacao com direito a credito - Vinculada a receitas tributadas e nao-tributadas no mercado interno, e de exportacao', 170, true),
    ('pis_cst', '60', '60', 'Credito presumido - Operacao de aquisicao vinculada exclusivamente a receita tributada no mercado interno', 180, true),
    ('pis_cst', '61', '61', 'Credito presumido - Operacao de aquisicao vinculada exclusivamente a receita nao-tributada no mercado interno', 190, true),
    ('pis_cst', '62', '62', 'Credito presumido - Operacao de aquisicao vinculada exclusivamente a receita de exportacao', 200, true),
    ('pis_cst', '63', '63', 'Credito presumido - Operacao de aquisicao vinculada a receitas tributadas e nao-tributadas no mercado interno', 210, true),
    ('pis_cst', '64', '64', 'Credito presumido - Operacao de aquisicao vinculada a receitas tributadas no mercado interno e de exportacao', 220, true),
    ('pis_cst', '65', '65', 'Credito presumido - Operacao de aquisicao vinculada a receitas nao-tributadas no mercado interno e de exportacao', 230, true),
    ('pis_cst', '66', '66', 'Credito presumido - Operacao de aquisicao vinculada a receitas tributadas e nao-tributadas no mercado interno, e de exportacao', 240, true),
    ('pis_cst', '67', '67', 'Credito presumido - Outras operacoes', 250, true),
    ('pis_cst', '70', '70', 'Operacao de aquisicao sem direito a credito', 260, true),
    ('pis_cst', '71', '71', 'Operacao de aquisicao com isencao', 270, true),
    ('pis_cst', '72', '72', 'Operacao de aquisicao com suspensao', 280, true),
    ('pis_cst', '73', '73', 'Operacao de aquisicao a aliquota zero', 290, true),
    ('pis_cst', '74', '74', 'Operacao de aquisicao sem incidencia da contribuicao', 300, true),
    ('pis_cst', '75', '75', 'Operacao de aquisicao por substituicao tributaria', 310, true),
    ('pis_cst', '98', '98', 'Outras operacoes de entrada', 320, true),
    ('pis_cst', '99', '99', 'Outras operacoes', 330, true),

    ('cofins_cst', '01', '01', 'Operacao tributavel com aliquota basica', 10, true),
    ('cofins_cst', '02', '02', 'Operacao tributavel com aliquota diferenciada', 20, true),
    ('cofins_cst', '03', '03', 'Operacao tributavel por unidade de medida de produto', 30, true),
    ('cofins_cst', '04', '04', 'Operacao tributavel monofasica - revenda a aliquota zero', 40, true),
    ('cofins_cst', '05', '05', 'Operacao tributavel por substituicao tributaria', 50, true),
    ('cofins_cst', '06', '06', 'Operacao tributavel a aliquota zero', 60, true),
    ('cofins_cst', '07', '07', 'Operacao isenta da contribuicao', 70, true),
    ('cofins_cst', '08', '08', 'Operacao sem incidencia da contribuicao', 80, true),
    ('cofins_cst', '09', '09', 'Operacao com suspensao da contribuicao', 90, true),
    ('cofins_cst', '49', '49', 'Outras operacoes de saida', 100, true),
    ('cofins_cst', '50', '50', 'Operacao com direito a credito - Vinculada exclusivamente a receita tributada no mercado interno', 110, true),
    ('cofins_cst', '51', '51', 'Operacao com direito a credito - Vinculada exclusivamente a receita nao-tributada no mercado interno', 120, true),
    ('cofins_cst', '52', '52', 'Operacao com direito a credito - Vinculada exclusivamente a receita de exportacao', 130, true),
    ('cofins_cst', '53', '53', 'Operacao com direito a credito - Vinculada a receitas tributadas e nao-tributadas no mercado interno', 140, true),
    ('cofins_cst', '54', '54', 'Operacao com direito a credito - Vinculada a receitas tributadas no mercado interno e de exportacao', 150, true),
    ('cofins_cst', '55', '55', 'Operacao com direito a credito - Vinculada a receitas nao-tributadas no mercado interno e de exportacao', 160, true),
    ('cofins_cst', '56', '56', 'Operacao com direito a credito - Vinculada a receitas tributadas e nao-tributadas no mercado interno, e de exportacao', 170, true),
    ('cofins_cst', '60', '60', 'Credito presumido - Operacao de aquisicao vinculada exclusivamente a receita tributada no mercado interno', 180, true),
    ('cofins_cst', '61', '61', 'Credito presumido - Operacao de aquisicao vinculada exclusivamente a receita nao-tributada no mercado interno', 190, true),
    ('cofins_cst', '62', '62', 'Credito presumido - Operacao de aquisicao vinculada exclusivamente a receita de exportacao', 200, true),
    ('cofins_cst', '63', '63', 'Credito presumido - Operacao de aquisicao vinculada a receitas tributadas e nao-tributadas no mercado interno', 210, true),
    ('cofins_cst', '64', '64', 'Credito presumido - Operacao de aquisicao vinculada a receitas tributadas no mercado interno e de exportacao', 220, true),
    ('cofins_cst', '65', '65', 'Credito presumido - Operacao de aquisicao vinculada a receitas nao-tributadas no mercado interno e de exportacao', 230, true),
    ('cofins_cst', '66', '66', 'Credito presumido - Operacao de aquisicao vinculada a receitas tributadas e nao-tributadas no mercado interno, e de exportacao', 240, true),
    ('cofins_cst', '67', '67', 'Credito presumido - Outras operacoes', 250, true),
    ('cofins_cst', '70', '70', 'Operacao de aquisicao sem direito a credito', 260, true),
    ('cofins_cst', '71', '71', 'Operacao de aquisicao com isencao', 270, true),
    ('cofins_cst', '72', '72', 'Operacao de aquisicao com suspensao', 280, true),
    ('cofins_cst', '73', '73', 'Operacao de aquisicao a aliquota zero', 290, true),
    ('cofins_cst', '74', '74', 'Operacao de aquisicao sem incidencia da contribuicao', 300, true),
    ('cofins_cst', '75', '75', 'Operacao de aquisicao por substituicao tributaria', 310, true),
    ('cofins_cst', '98', '98', 'Outras operacoes de entrada', 320, true),
    ('cofins_cst', '99', '99', 'Outras operacoes', 330, true)
ON CONFLICT (catalog_type, code) DO UPDATE
   SET label = EXCLUDED.label,
       description = EXCLUDED.description,
       sort_order = EXCLUDED.sort_order,
       is_active = EXCLUDED.is_active,
       updated_at = NOW();
